import Navbar from "@/components/Navbar";
import "../styles/main.scss";


export const metadata = {
  title: "WebDeveloper |Uncle Moses",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
